name: example
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route:
    path: ../auto_route/


dev_dependencies:
  build_runner:

  flutter_test:
    sdk: flutter
  auto_route_generator:
    path: ../auto_route_generator

flutter:
  uses-material-design: true
