builders:
  autoRouteGenerator:
    import: "package:auto_route_annotation/builder.dart"
    builder_factories: ["autoRouteGenerator"]
    build_extensions: {'.dart': ['.auto_route_config.dart']}
    auto_apply: dependents
    build_to: cache

#  transitionGenerator:
#    import: "package:auto_route_annotation/builder.dart"
#    builder_factories: ["transitionGenerator"]
#    build_extensions: {'.dart': ['.transition_config.dart']}
#    auto_apply: dependents
#    build_to: cache
#post_process_builders:
#  router_file_generator:
#    import: "package:auto_route_annotation/builder.dart"
#    builder_factory: "routerFileGeneratorBuilder"
#    input_extensions: [".auto_route_config.json"]
