name: auto_route_annotation
description: A new Flutter package.
version: 0.0.1
author:
homepage: <milad.akarie@gmail.com>

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  build: '>=0.12.0 <2.0.0'
  source_gen: ^0.9.4+6
  glob:
  auto_route:
    path: ../auto_route/


dev_dependencies:
  build_runner:

