builders:
  autoRouteGenerator:
    import: "package:auto_route_generator/builder.dart"
    builder_factories: ["autoRouteGenerator"]
    build_extensions: {'.dart': ['.auto_route.dart']}
    auto_apply: dependents
    build_to: cache