builders:
  autoRouteGenerator:
    import: "package:auto_route_generator/builder.dart"
    builder_factories: ["autoRouteGenerator"]
    build_extensions: {'.json': ['.auto_route.json']}
    auto_apply: dependents
    build_to: cache
